// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dyxjtbsjrjqcvlbkicha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5eGp0YnNqcmpxY3ZsYmtpY2hhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU5Njg4NjIsImV4cCI6MjA4MTU0NDg2Mn0.8U0i4zn_KuTB1gyHltnUskJddA8C2OqSgQJH9pCCs70";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});